#!/bin/sh

lb config \
  --mode debian \
  --distribution bookworm \
  --architectures amd64 \
  --binary-images iso-hybrid \
  --debian-installer false \
  --bootappend-live "boot=live components quiet" \
  --archive-areas "main contrib non-free non-free-firmware"
