name: Build JustinOS ISO

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 下載專案
      uses: actions/checkout@v3

    - name: 安裝 live-build
      run: |
        sudo apt update
        sudo apt install -y live-build

    - name: 設定權限
      run: |
        chmod +x auto/config
        chmod +x auto/build

    - name: 建置 ISO
      run: |
        sudo auto/config
        sudo auto/build

    - name: 上傳 ISO
      uses: actions/upload-artifact@v4
      with:
        name: JustinOS
        path: live-image-amd64.hybrid.iso
